export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const REMOVE_FROM_CART_REQUESTED = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILED = 'REMOVE_FROM_CART_FAILED';

export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';

export const PRODUCT_REQUESTED = 'PRODUCT_REQUESTED';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';

export const SEARCH_PRODUCT_REQUESTED = 'SEARCH_PRODUCT_REQUESTED';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILED = 'SEARCH_PRODUCT_FAILED';